/**
 * cloudinary.ts — GETKEJA media upload utility
 *
 * Wraps the Cloudinary Node SDK.  All property media (photos, videos,
 * floor plans, virtual tours, drone footage) flows through here before
 * any URL is written to the database.
 *
 * Design decisions:
 *  - Each property gets its own Cloudinary folder: `getkeja/properties/{propertyId}/`
 *  - Media type sub-folders keep assets organised: `.../photos/`, `.../videos/` etc.
 *  - Every upload returns a `CloudinaryUploadResult` that maps 1-to-1 with the
 *    columns in `property_media` (url, thumbnail_url, media_type).
 *  - Videos are uploaded with `resource_type: 'video'`; everything else is `image`.
 *  - Thumbnails for videos are auto-generated by Cloudinary at upload time.
 *  - File size limits are enforced before the upload hits the network.
 *  - Public IDs are deterministic: `{folder}/{uuid}` — idempotent re-uploads
 *    replace the previous asset instead of creating duplicates.
 */

import { v2 as cloudinary, type UploadApiResponse } from 'cloudinary';
import { env }    from '../config/environment.js';
import { logger } from './logger.js';

// ─────────────────────────────────────────────────────────────────────────────
// SDK configuration  (runs once at module load)
// ─────────────────────────────────────────────────────────────────────────────
cloudinary.config({
  cloud_name: env.cloudinary.cloudName,
  api_key:    env.cloudinary.apiKey,
  api_secret: env.cloudinary.apiSecret,
  secure:     true,   // always use https:// URLs
});

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export type PropertyMediaType = 'photo' | 'video' | 'floor_plan' | 'virtual_tour' | 'drone';

export interface CloudinaryUploadResult {
  /** Full delivery URL (https). Stored in property_media.url */
  url:           string;
  /** Auto-generated thumbnail URL. Stored in property_media.thumbnail_url */
  thumbnail_url: string | null;
  /** Cloudinary public_id — useful for future deletions */
  public_id:     string;
  /** Width in pixels (images only) */
  width:         number | null;
  /** Height in pixels (images only) */
  height:        number | null;
  /** Duration in seconds (videos only) */
  duration:      number | null;
  /** File size in bytes */
  bytes:         number;
  /** Resource type returned by Cloudinary: 'image' | 'video' | 'raw' */
  resource_type: string;
  /** Original filename */
  original_filename: string;
}

export interface MediaUploadOptions {
  /** Maps to a Cloudinary sub-folder under getkeja/properties/{propertyId}/ */
  mediaType:   PropertyMediaType;
  propertyId:  string;
  /** Optional override for the Cloudinary public_id suffix (default: uuid) */
  publicIdSuffix?: string;
  /** Whether this is the cover image — used for eager transforms */
  isCover?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

/** Maximum file sizes — enforced before upload hits the network */
const MAX_IMAGE_BYTES = 15 * 1024 * 1024;   // 15 MB
const MAX_VIDEO_BYTES = 200 * 1024 * 1024;  // 200 MB

/** Cloudinary resource type per media type */
const RESOURCE_TYPE_MAP: Record<PropertyMediaType, 'image' | 'video'> = {
  photo:        'image',
  floor_plan:   'image',
  virtual_tour: 'image',  // 360 images are still "image" type in Cloudinary
  drone:        'video',
  video:        'video',
};

/** Sub-folder within the property folder */
const SUBFOLDER_MAP: Record<PropertyMediaType, string> = {
  photo:        'photos',
  video:        'videos',
  floor_plan:   'floor_plans',
  virtual_tour: 'virtual_tours',
  drone:        'drone',
};

// ─────────────────────────────────────────────────────────────────────────────
// Core upload function
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Upload a single file (provided as a base64 data URI or a remote URL) to
 * Cloudinary and return the structured result ready for DB insertion.
 *
 * @param fileSource  base64 data URI (`data:image/jpeg;base64,...`) or https URL
 * @param options     upload metadata
 */
export async function uploadPropertyMedia(
  fileSource: string,
  options: MediaUploadOptions,
): Promise<CloudinaryUploadResult> {
  const { mediaType, propertyId, publicIdSuffix, isCover = false } = options;

  const resourceType = RESOURCE_TYPE_MAP[mediaType];
  const subfolder    = SUBFOLDER_MAP[mediaType];
  const suffix       = publicIdSuffix ?? crypto.randomUUID();
  const folder       = `getkeja/properties/${propertyId}/${subfolder}`;
  const publicId     = `${folder}/${suffix}`;

  // ── Size guard for base64 uploads ────────────────────────────────────────
  if (fileSource.startsWith('data:')) {
    // base64 string length * 0.75 ≈ actual byte size
    const estimatedBytes = (fileSource.length * 3) / 4;
    const limit = resourceType === 'video' ? MAX_VIDEO_BYTES : MAX_IMAGE_BYTES;
    if (estimatedBytes > limit) {
      const limitMb = Math.round(limit / 1024 / 1024);
      throw new Error(`File too large. Maximum size for ${mediaType} is ${limitMb} MB`);
    }
  }

  // ── Eager transformations ─────────────────────────────────────────────────
  // Cover photos get an optimised WebP thumbnail at 800×600 for listing cards.
  // Videos get a JPG poster frame at 0 seconds.
  const eager =
    resourceType === 'image'
      ? isCover
        ? [{ width: 800, height: 600, crop: 'fill', format: 'webp', quality: 'auto' }]
        : [{ width: 400, height: 300, crop: 'fill', format: 'webp', quality: 'auto' }]
      : [{ width: 640, height: 360, crop: 'fill', format: 'jpg', start_offset: '0' }];

  logger.info({ propertyId, mediaType, publicId }, 'cloudinary.upload.start');

  let result: UploadApiResponse;
  try {
    result = await cloudinary.uploader.upload(fileSource, {
      public_id:     publicId,
      resource_type: resourceType,
      folder,        // redundant with public_id but makes the dashboard cleaner
      overwrite:     true,
      eager,
      eager_async:   false,  // wait for eager transforms before returning
      // Automatic quality & format optimisation
      quality:       'auto',
      fetch_format:  resourceType === 'image' ? 'auto' : undefined,
      // Embed useful metadata
      context: {
        property_id: propertyId,
        media_type:  mediaType,
      },
      // Tag for bulk operations
      tags: [`property_${propertyId}`, `type_${mediaType}`],
    });
  } catch (err: any) {
    logger.error({ err: err?.message, propertyId, mediaType }, 'cloudinary.upload.failed');
    throw new Error(`Media upload failed: ${err?.message ?? 'Cloudinary error'}`);
  }

  // ── Build thumbnail URL ───────────────────────────────────────────────────
  // For images: use the eager transform result (400×300 WebP)
  // For videos: use the eager poster frame
  const thumbnailUrl =
    result.eager?.[0]?.secure_url ??
    (resourceType === 'video'
      ? cloudinary.url(result.public_id, {
          resource_type: 'video',
          format:        'jpg',
          transformation: [{ width: 640, height: 360, crop: 'fill', start_offset: '0' }],
        })
      : null);

  logger.info(
    { propertyId, mediaType, publicId: result.public_id, bytes: result.bytes },
    'cloudinary.upload.success',
  );

  return {
    url:               result.secure_url,
    thumbnail_url:     thumbnailUrl,
    public_id:         result.public_id,
    width:             result.width             ?? null,
    height:            result.height            ?? null,
    duration:          (result as any).duration ?? null,
    bytes:             result.bytes,
    resource_type:     result.resource_type,
    original_filename: result.original_filename ?? '',
  };
}

/**
 * Upload multiple files concurrently (max 10 in parallel to stay within
 * Cloudinary's rate limits on the free/starter tier).
 */
export async function uploadPropertyMediaBatch(
  files: Array<{ fileSource: string; options: MediaUploadOptions }>,
): Promise<CloudinaryUploadResult[]> {
  const CONCURRENCY = 10;
  const results: CloudinaryUploadResult[] = [];

  for (let i = 0; i < files.length; i += CONCURRENCY) {
    const chunk = files.slice(i, i + CONCURRENCY);
    const settled = await Promise.allSettled(
      chunk.map(({ fileSource, options }) => uploadPropertyMedia(fileSource, options)),
    );

    for (const outcome of settled) {
      if (outcome.status === 'fulfilled') {
        results.push(outcome.value);
      } else {
        // Log individual failure but don't abort the whole batch
        logger.error({ reason: outcome.reason }, 'cloudinary.batch.partial_failure');
        throw new Error(outcome.reason?.message ?? 'One or more uploads failed');
      }
    }
  }

  return results;
}

/**
 * Delete a media asset from Cloudinary by its public_id.
 * Called when a property is deleted or a specific media item is removed.
 */
export async function deletePropertyMedia(
  publicId: string,
  resourceType: 'image' | 'video' = 'image',
): Promise<void> {
  try {
    await cloudinary.uploader.destroy(publicId, { resource_type: resourceType });
    logger.info({ publicId, resourceType }, 'cloudinary.delete.success');
  } catch (err: any) {
    // Non-fatal — log and continue.  The DB row will still be removed.
    logger.error({ err: err?.message, publicId }, 'cloudinary.delete.failed');
  }
}

/**
 * Delete all media for a property by tag (used on property soft-delete).
 * Cloudinary's `delete_resources_by_tag` API deletes all assets with the tag.
 */
export async function deletePropertyMediaByTag(propertyId: string): Promise<void> {
  const tag = `property_${propertyId}`;
  try {
    await cloudinary.api.delete_resources_by_tag(tag, { resource_type: 'image' });
    await cloudinary.api.delete_resources_by_tag(tag, { resource_type: 'video' });
    logger.info({ propertyId, tag }, 'cloudinary.delete_by_tag.success');
  } catch (err: any) {
    logger.error({ err: err?.message, propertyId }, 'cloudinary.delete_by_tag.failed');
  }
}